### ISSUE TITLE
No License

### ISSUE THREAD

**Issue by peterennis** [didinj/Ionic2AccordionList#1]
Please add it.

**Comment by didinj** [comment]
Done. Thank you!

**Comment by peterennis** [comment]
GPL is "viral", Ref: https://en.wikipedia.org/wiki/Viral_license
The most common, with least restriction is MIT.
If you want the code more widely used, but really love GPL then you could dual license it.

**Comment by didinj** [comment]
I have changed to MIT. Thank You!

**Comment by peterennis** [comment]
Thanks,
